-- 20260731_tenant_rls_floor.sql -- SECURITY FLOOR: tenant-scoped RLS on leads + 19 children. Staff see their tenant; customer sees own lead via access_token; admin global. Helpers user_is_admin/has_tenant_access/can_see_lead/own_lead.

create or replace function public.can_see_lead(p_lead uuid) returns boolean language sql stable security definer set search_path to 'public','extensions' as $f$
  select exists(select 1 from public.leads l where l.id=p_lead and (
     public.has_tenant_access(auth.uid(), l.tenant_id)
     or (l.access_token is not null and l.access_token = ((current_setting('request.headers',true))::json->>'x-access-token'))));
$f$;
create or replace function public.own_lead(p_lead uuid) returns boolean language sql stable security definer set search_path to 'public','extensions' as $f$
  select exists(select 1 from public.leads l where l.id=p_lead and public.has_tenant_access(auth.uid(), l.tenant_id));
$f$;

drop policy if exists "Authenticated users can create activity logs" on public.activity_logs;
drop policy if exists "Customers can view activity logs for their own leads" on public.activity_logs;
drop policy if exists "Staff can view all activity logs" on public.activity_logs;
drop policy if exists "Service role can manage agent_queue" on public.agent_queue;
drop policy if exists "Service role can write agent_runs" on public.agent_runs;
drop policy if exists "Staff can read agent_runs" on public.agent_runs;
drop policy if exists "Admins can delete assignments" on public.assignments;
drop policy if exists "Consultants and admins can create assignments" on public.assignments;
drop policy if exists "Consultants and installers can update assignments" on public.assignments;
drop policy if exists "Staff can view assignments" on public.assignments;
drop policy if exists "assignments_insert_staff_only" on public.assignments;
drop policy if exists "assignments_update_staff_only" on public.assignments;
drop policy if exists "Admins can delete contracts" on public.contracts;
drop policy if exists "Authenticated users can create contracts" on public.contracts;
drop policy if exists "Users can view related contracts" on public.contracts;
drop policy if exists "contracts_insert_staff_only" on public.contracts;
drop policy if exists "conversations_staff" on public.conversations;
drop policy if exists "esb_submissions_read" on public.esb_submissions;
drop policy if exists "esb_submissions_write" on public.esb_submissions;
drop policy if exists "Authenticated users can create checklists" on public.installation_checklists;
drop policy if exists "Authenticated users can update checklists" on public.installation_checklists;
drop policy if exists "Authenticated users can view checklists" on public.installation_checklists;
drop policy if exists "Staff can view installation_checklists" on public.installation_checklists;
drop policy if exists "installation_checklists_insert_staff_only" on public.installation_checklists;
drop policy if exists "installation_checklists_update_staff_or_assigned" on public.installation_checklists;
drop policy if exists "installed_equipment_read" on public.installed_equipment;
drop policy if exists "installed_equipment_write" on public.installed_equipment;
drop policy if exists "Admins can delete invoices" on public.invoices;
drop policy if exists "Consultants and admins can create invoices" on public.invoices;
drop policy if exists "Related users can update invoices" on public.invoices;
drop policy if exists "Users can view related invoices" on public.invoices;
drop policy if exists "lead_documents_staff" on public.lead_documents;
drop policy if exists "Consultants and admins can read lead_intake" on public.lead_intake;
drop policy if exists "Consultants and admins can write lead_intake" on public.lead_intake;
drop policy if exists "Customer portal can read own lead_intake" on public.lead_intake;
drop policy if exists "touchpoints_staff" on public.lead_touchpoints;
drop policy if exists "Authenticated users can update lead access_token" on public.leads;
drop policy if exists "Public can view leads by access_token" on public.leads;
drop policy if exists "leads_delete_admin_only" on public.leads;
drop policy if exists "leads_insert_authenticated" on public.leads;
drop policy if exists "leads_select_staff_or_owner" on public.leads;
drop policy if exists "leads_update_staff_or_owner" on public.leads;
drop policy if exists "Service role can create any notification" on public.notifications;
drop policy if exists "Users can create own notifications" on public.notifications;
drop policy if exists "Users can delete own notifications" on public.notifications;
drop policy if exists "Users can update own notifications" on public.notifications;
drop policy if exists "Users can view own notifications" on public.notifications;
drop policy if exists "notifications_insert_self" on public.notifications;
drop policy if exists "notifications_insert_service_role" on public.notifications;
drop policy if exists "Authenticated users can insert project documents" on public.project_documents;
drop policy if exists "Authenticated users can view project documents" on public.project_documents;
drop policy if exists "Uploaders and admins can delete project documents" on public.project_documents;
drop policy if exists "Admins can delete proposals" on public.proposals;
drop policy if exists "Authenticated users can view all proposals" on public.proposals;
drop policy if exists "Consultants can create proposals" on public.proposals;
drop policy if exists "Consultants can update their proposals" on public.proposals;
drop policy if exists "Staff can view proposals" on public.proposals;
drop policy if exists "Consultants and admins can create SEAI applications" on public.seai_applications;
drop policy if exists "Consultants and admins can update SEAI applications" on public.seai_applications;
drop policy if exists "Users can view related SEAI applications" on public.seai_applications;
drop policy if exists "Admins can delete surveys" on public.site_surveys;
drop policy if exists "Authenticated users can create surveys" on public.site_surveys;
drop policy if exists "Surveyors can update their surveys" on public.site_surveys;
drop policy if exists "Users can view related surveys" on public.site_surveys;
drop policy if exists "Consultants can write touchpoints for assigned leads" on public.touchpoints;
drop policy if exists "Customer can read own touchpoints" on public.touchpoints;
drop policy if exists "Service role can write touchpoints" on public.touchpoints;
drop policy if exists "Staff can read touchpoints" on public.touchpoints;
drop policy if exists "touchpoints_insert_service_or_staff_or_self" on public.touchpoints;
create policy leads_sel on public.leads for select using (public.has_tenant_access(auth.uid(),tenant_id) or (access_token is not null and access_token=((current_setting('request.headers',true))::json->>'x-access-token')));
create policy leads_ins on public.leads for insert with check (public.has_tenant_access(auth.uid(),tenant_id));
create policy leads_upd on public.leads for update using (public.has_tenant_access(auth.uid(),tenant_id)) with check (public.has_tenant_access(auth.uid(),tenant_id));
create policy leads_del on public.leads for delete using (public.has_tenant_access(auth.uid(),tenant_id));
create policy activity_logs_sel on public.activity_logs for select using (public.can_see_lead(lead_id));
create policy activity_logs_ins on public.activity_logs for insert with check (public.own_lead(lead_id));
create policy activity_logs_upd on public.activity_logs for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy activity_logs_del on public.activity_logs for delete using (public.own_lead(lead_id));
create policy agent_queue_sel on public.agent_queue for select using (public.can_see_lead(lead_id));
create policy agent_queue_ins on public.agent_queue for insert with check (public.own_lead(lead_id));
create policy agent_queue_upd on public.agent_queue for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy agent_queue_del on public.agent_queue for delete using (public.own_lead(lead_id));
create policy agent_runs_sel on public.agent_runs for select using (public.can_see_lead(lead_id));
create policy agent_runs_ins on public.agent_runs for insert with check (public.own_lead(lead_id));
create policy agent_runs_upd on public.agent_runs for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy agent_runs_del on public.agent_runs for delete using (public.own_lead(lead_id));
create policy assignments_sel on public.assignments for select using (public.can_see_lead(lead_id));
create policy assignments_ins on public.assignments for insert with check (public.own_lead(lead_id));
create policy assignments_upd on public.assignments for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy assignments_del on public.assignments for delete using (public.own_lead(lead_id));
create policy contracts_sel on public.contracts for select using (public.can_see_lead(lead_id));
create policy contracts_ins on public.contracts for insert with check (public.own_lead(lead_id));
create policy contracts_upd on public.contracts for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy contracts_del on public.contracts for delete using (public.own_lead(lead_id));
create policy conversations_sel on public.conversations for select using (public.can_see_lead(lead_id));
create policy conversations_ins on public.conversations for insert with check (public.own_lead(lead_id));
create policy conversations_upd on public.conversations for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy conversations_del on public.conversations for delete using (public.own_lead(lead_id));
create policy esb_submissions_sel on public.esb_submissions for select using (public.can_see_lead(lead_id));
create policy esb_submissions_ins on public.esb_submissions for insert with check (public.own_lead(lead_id));
create policy esb_submissions_upd on public.esb_submissions for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy esb_submissions_del on public.esb_submissions for delete using (public.own_lead(lead_id));
create policy installation_checklists_sel on public.installation_checklists for select using (public.can_see_lead(lead_id));
create policy installation_checklists_ins on public.installation_checklists for insert with check (public.own_lead(lead_id));
create policy installation_checklists_upd on public.installation_checklists for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy installation_checklists_del on public.installation_checklists for delete using (public.own_lead(lead_id));
create policy installed_equipment_sel on public.installed_equipment for select using (public.can_see_lead(lead_id));
create policy installed_equipment_ins on public.installed_equipment for insert with check (public.own_lead(lead_id));
create policy installed_equipment_upd on public.installed_equipment for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy installed_equipment_del on public.installed_equipment for delete using (public.own_lead(lead_id));
create policy invoices_sel on public.invoices for select using (public.can_see_lead(lead_id));
create policy invoices_ins on public.invoices for insert with check (public.own_lead(lead_id));
create policy invoices_upd on public.invoices for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy invoices_del on public.invoices for delete using (public.own_lead(lead_id));
create policy lead_documents_sel on public.lead_documents for select using (public.can_see_lead(lead_id));
create policy lead_documents_ins on public.lead_documents for insert with check (public.own_lead(lead_id));
create policy lead_documents_upd on public.lead_documents for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy lead_documents_del on public.lead_documents for delete using (public.own_lead(lead_id));
create policy lead_intake_sel on public.lead_intake for select using (public.can_see_lead(lead_id));
create policy lead_intake_ins on public.lead_intake for insert with check (public.own_lead(lead_id));
create policy lead_intake_upd on public.lead_intake for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy lead_intake_del on public.lead_intake for delete using (public.own_lead(lead_id));
create policy lead_touchpoints_sel on public.lead_touchpoints for select using (public.can_see_lead(lead_id));
create policy lead_touchpoints_ins on public.lead_touchpoints for insert with check (public.own_lead(lead_id));
create policy lead_touchpoints_upd on public.lead_touchpoints for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy lead_touchpoints_del on public.lead_touchpoints for delete using (public.own_lead(lead_id));
create policy notifications_sel on public.notifications for select using (public.can_see_lead(lead_id));
create policy notifications_ins on public.notifications for insert with check (public.own_lead(lead_id));
create policy notifications_upd on public.notifications for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy notifications_del on public.notifications for delete using (public.own_lead(lead_id));
create policy project_documents_sel on public.project_documents for select using (public.can_see_lead(lead_id));
create policy project_documents_ins on public.project_documents for insert with check (public.own_lead(lead_id));
create policy project_documents_upd on public.project_documents for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy project_documents_del on public.project_documents for delete using (public.own_lead(lead_id));
create policy proposals_sel on public.proposals for select using (public.can_see_lead(lead_id));
create policy proposals_ins on public.proposals for insert with check (public.own_lead(lead_id));
create policy proposals_upd on public.proposals for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy proposals_del on public.proposals for delete using (public.own_lead(lead_id));
create policy seai_applications_sel on public.seai_applications for select using (public.can_see_lead(lead_id));
create policy seai_applications_ins on public.seai_applications for insert with check (public.own_lead(lead_id));
create policy seai_applications_upd on public.seai_applications for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy seai_applications_del on public.seai_applications for delete using (public.own_lead(lead_id));
create policy site_surveys_sel on public.site_surveys for select using (public.can_see_lead(lead_id));
create policy site_surveys_ins on public.site_surveys for insert with check (public.own_lead(lead_id));
create policy site_surveys_upd on public.site_surveys for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy site_surveys_del on public.site_surveys for delete using (public.own_lead(lead_id));
create policy touchpoints_sel on public.touchpoints for select using (public.can_see_lead(lead_id));
create policy touchpoints_ins on public.touchpoints for insert with check (public.own_lead(lead_id));
create policy touchpoints_upd on public.touchpoints for update using (public.own_lead(lead_id)) with check (public.own_lead(lead_id));
create policy touchpoints_del on public.touchpoints for delete using (public.own_lead(lead_id));